/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectomundial;

/**
 *
 * @author User
 */
public class xddd extends javax.swing.JPanel {

    /**
     * Creates new form xddd
     */
    public xddd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Jpartidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Jgoles = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        tfpc2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        tfpc3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        tfpc4 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        JMenosGoles = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        JMasGoles = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        JEmpatados = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        JGanados = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        JSelecMenosGol = new javax.swing.JTextField();
        JSelecMasGol = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        JMenosP = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        JMasPuntos = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        JContMenos = new javax.swing.JTextField();
        JContMas = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 427));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CARGADOS");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 70, 20));

        Jpartidos.setBackground(new java.awt.Color(204, 204, 255));
        Jpartidos.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        Jpartidos.setForeground(new java.awt.Color(0, 0, 0));
        Jpartidos.setText("32");
        Jpartidos.setBorder(null);
        Jpartidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JpartidosActionPerformed(evt);
            }
        });
        jPanel3.add(Jpartidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 60, 50));

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("NUMERO DE PARTIDOS");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 150, 110));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(140, 100));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("POR PARTIDO");

        Jgoles.setBackground(new java.awt.Color(204, 204, 255));
        Jgoles.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        Jgoles.setForeground(new java.awt.Color(0, 0, 0));
        Jgoles.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Jgoles.setText("32");
        Jgoles.setBorder(null);
        Jgoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JgolesActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PROMEDIO DE GOLES");

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("POR PARTIDO");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 20));

        tfpc2.setBackground(new java.awt.Color(204, 204, 255));
        tfpc2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        tfpc2.setForeground(new java.awt.Color(0, 0, 0));
        tfpc2.setText("32");
        tfpc2.setBorder(null);
        tfpc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpc2ActionPerformed(evt);
            }
        });
        jPanel4.add(tfpc2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, 88));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PROMEDIO DE GOLES");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        jPanel5.setBackground(new java.awt.Color(204, 204, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("POR PARTIDO");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 20));

        tfpc3.setBackground(new java.awt.Color(204, 204, 255));
        tfpc3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        tfpc3.setForeground(new java.awt.Color(0, 0, 0));
        tfpc3.setText("32");
        tfpc3.setBorder(null);
        tfpc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpc3ActionPerformed(evt);
            }
        });
        jPanel5.add(tfpc3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, 88));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("PROMEDIO DE GOLES");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("POR PARTIDO");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 90, 20));

        tfpc4.setBackground(new java.awt.Color(204, 204, 255));
        tfpc4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        tfpc4.setForeground(new java.awt.Color(0, 0, 0));
        tfpc4.setText("32");
        tfpc4.setBorder(null);
        tfpc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfpc4ActionPerformed(evt);
            }
        });
        jPanel6.add(tfpc4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 60, 88));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("PROMEDIO DE GOLES");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 160, 20));

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 150, 120));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Jgoles, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Jgoles, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 150, 110));

        jPanel7.setBackground(new java.awt.Color(204, 204, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JMenosGoles.setBackground(new java.awt.Color(204, 204, 255));
        JMenosGoles.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        JMenosGoles.setForeground(new java.awt.Color(0, 0, 0));
        JMenosGoles.setText("32");
        JMenosGoles.setBorder(null);
        JMenosGoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenosGolesActionPerformed(evt);
            }
        });
        jPanel7.add(JMenosGoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 30, 20));

        jLabel12.setBackground(new java.awt.Color(0, 0, 0));
        jLabel12.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("MENOS GOLES");
        jPanel7.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 20));

        jLabel13.setBackground(new java.awt.Color(0, 0, 0));
        jLabel13.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("PARTIDOS");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 60, 20));

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("MAS GOLES");
        jPanel7.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 20));

        JMasGoles.setBackground(new java.awt.Color(204, 204, 255));
        JMasGoles.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        JMasGoles.setForeground(new java.awt.Color(0, 0, 0));
        JMasGoles.setText("32");
        JMasGoles.setBorder(null);
        JMasGoles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMasGolesActionPerformed(evt);
            }
        });
        jPanel7.add(JMasGoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 30, 20));

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 170, 110));

        jPanel9.setBackground(new java.awt.Color(204, 204, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JEmpatados.setBackground(new java.awt.Color(204, 204, 255));
        JEmpatados.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        JEmpatados.setForeground(new java.awt.Color(0, 0, 0));
        JEmpatados.setText("32");
        JEmpatados.setBorder(null);
        JEmpatados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JEmpatadosActionPerformed(evt);
            }
        });
        jPanel9.add(JEmpatados, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 30, 20));

        jLabel15.setBackground(new java.awt.Color(0, 0, 0));
        jLabel15.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("EMPATADOS");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 20));

        jLabel17.setBackground(new java.awt.Color(0, 0, 0));
        jLabel17.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("NUMERO DE PARTIDOS:");
        jPanel9.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setText("GANADOS");
        jPanel9.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 20));

        JGanados.setBackground(new java.awt.Color(204, 204, 255));
        JGanados.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        JGanados.setForeground(new java.awt.Color(0, 0, 0));
        JGanados.setText("32");
        JGanados.setBorder(null);
        JGanados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JGanadosActionPerformed(evt);
            }
        });
        jPanel9.add(JGanados, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 30, 20));

        add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 180, 110));

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("MENOS GOLES");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 20));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setText("SELECCION NACIONAL CON");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setText("MAS GOLES");
        jPanel10.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 20));

        JSelecMenosGol.setBackground(new java.awt.Color(204, 204, 255));
        JSelecMenosGol.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        JSelecMenosGol.setForeground(new java.awt.Color(0, 0, 0));
        JSelecMenosGol.setText("ARGENTINA");
        JSelecMenosGol.setBorder(null);
        JSelecMenosGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSelecMenosGolActionPerformed(evt);
            }
        });
        jPanel10.add(JSelecMenosGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 70, 20));

        JSelecMasGol.setBackground(new java.awt.Color(204, 204, 255));
        JSelecMasGol.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        JSelecMasGol.setForeground(new java.awt.Color(0, 0, 0));
        JSelecMasGol.setText("ARGENTINA");
        JSelecMasGol.setBorder(null);
        JSelecMasGol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JSelecMasGolActionPerformed(evt);
            }
        });
        jPanel10.add(JSelecMasGol, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 70, 20));

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 200, 110));

        jPanel11.setBackground(new java.awt.Color(204, 204, 255));
        jPanel11.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JMenosP.setBackground(new java.awt.Color(204, 204, 255));
        JMenosP.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        JMenosP.setForeground(new java.awt.Color(0, 0, 0));
        JMenosP.setText("32");
        JMenosP.setBorder(null);
        JMenosP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenosPActionPerformed(evt);
            }
        });
        jPanel11.add(JMenosP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 80, 20));

        jLabel21.setBackground(new java.awt.Color(0, 0, 0));
        jLabel21.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setText("MENOS PUNTOS");
        jPanel11.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 100, 20));

        jLabel22.setBackground(new java.awt.Color(0, 0, 0));
        jLabel22.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setText("SELECCION NACIONAL CON");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jLabel23.setBackground(new java.awt.Color(0, 0, 0));
        jLabel23.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setText("MAS PUNTOS");
        jPanel11.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 80, 20));

        JMasPuntos.setBackground(new java.awt.Color(204, 204, 255));
        JMasPuntos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        JMasPuntos.setForeground(new java.awt.Color(0, 0, 0));
        JMasPuntos.setText("32");
        JMasPuntos.setBorder(null);
        JMasPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMasPuntosActionPerformed(evt);
            }
        });
        jPanel11.add(JMasPuntos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 90, 20));

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 210, 110));

        jPanel12.setBackground(new java.awt.Color(204, 204, 255));
        jPanel12.setPreferredSize(new java.awt.Dimension(140, 100));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(0, 0, 0));
        jLabel24.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setText("MENOS GOLES");
        jPanel12.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 90, 20));

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("CONTINENTES CON");
        jPanel12.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 20));

        jLabel26.setBackground(new java.awt.Color(0, 0, 0));
        jLabel26.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(0, 0, 0));
        jLabel26.setText("MAS GOLES");
        jPanel12.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 70, 20));

        JContMenos.setBackground(new java.awt.Color(204, 204, 255));
        JContMenos.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        JContMenos.setForeground(new java.awt.Color(0, 0, 0));
        JContMenos.setText("ARGENTINA");
        JContMenos.setBorder(null);
        JContMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JContMenosActionPerformed(evt);
            }
        });
        jPanel12.add(JContMenos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 70, 20));

        JContMas.setBackground(new java.awt.Color(204, 204, 255));
        JContMas.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        JContMas.setForeground(new java.awt.Color(0, 0, 0));
        JContMas.setText("ARGENTINA");
        JContMas.setBorder(null);
        JContMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JContMasActionPerformed(evt);
            }
        });
        jPanel12.add(JContMas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 70, 20));

        add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 210, 110));
    }// </editor-fold>//GEN-END:initComponents

    private void JpartidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JpartidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JpartidosActionPerformed

    private void JgolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JgolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JgolesActionPerformed

    private void tfpc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpc2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpc2ActionPerformed

    private void tfpc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpc3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpc3ActionPerformed

    private void tfpc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfpc4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfpc4ActionPerformed

    private void JMenosGolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenosGolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenosGolesActionPerformed

    private void JMasGolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMasGolesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMasGolesActionPerformed

    private void JEmpatadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JEmpatadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JEmpatadosActionPerformed

    private void JGanadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JGanadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JGanadosActionPerformed

    private void JSelecMenosGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSelecMenosGolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JSelecMenosGolActionPerformed

    private void JSelecMasGolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JSelecMasGolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JSelecMasGolActionPerformed

    private void JMenosPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenosPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenosPActionPerformed

    private void JMasPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMasPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMasPuntosActionPerformed

    private void JContMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JContMenosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JContMenosActionPerformed

    private void JContMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JContMasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JContMasActionPerformed

    public void actualizar(String partidos, String promedio, String masGol, String menosGol, String partidosGan, String partidosEmp, String selecMas, String selecMenos, String contMas, String contMenos, String selecMasP, String selecMenosP){
        Jpartidos.setText(partidos);
        Jgoles.setText(promedio);
        JMasGoles.setText(masGol);
        JMenosGoles.setText(menosGol);
        JGanados.setText(partidosGan);
        JEmpatados.setText(partidosEmp);
        JSelecMasGol.setText(selecMas);
        JSelecMenosGol.setText(selecMenos);
        JContMas.setText(contMas);
        JContMenos.setText(contMenos);
        JMasPuntos.setText(selecMasP);
        JMenosP.setText(selecMenosP);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JContMas;
    private javax.swing.JTextField JContMenos;
    private javax.swing.JTextField JEmpatados;
    private javax.swing.JTextField JGanados;
    private javax.swing.JTextField JMasGoles;
    private javax.swing.JTextField JMasPuntos;
    private javax.swing.JTextField JMenosGoles;
    private javax.swing.JTextField JMenosP;
    private javax.swing.JTextField JSelecMasGol;
    private javax.swing.JTextField JSelecMenosGol;
    private javax.swing.JTextField Jgoles;
    private javax.swing.JTextField Jpartidos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField tfpc2;
    private javax.swing.JTextField tfpc3;
    private javax.swing.JTextField tfpc4;
    // End of variables declaration//GEN-END:variables
}
